import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import SessionProvider from "./components/SessionProvider";
import type { ReactNode } from "react";
import { getServerSession } from "next-auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session  = await getServerSession();
  return (
    <html lang="en">
        <body className={inter.className}>
          <SessionProvider session={session}>
            <main className="">
              <Providers>
                {children}
              </Providers>
            </main>
          </SessionProvider>
        </body>
    </html>
  );
}
